export const FINAL_REVIEW_MAX_REASON_CODE_UNITS = 2_000 as const;
export const FINAL_REVIEW_MAX_INPUT_TEXT_CODE_UNITS = 12_000 as const;
export const FINAL_REVIEW_MAX_ARRAY_ITEMS = 64 as const;
export const FINAL_REVIEW_MAX_UNQUOTED_COPY_CODE_UNITS = 200 as const;
export const FINAL_REVIEW_MAX_ALLOWED_QUOTE_CODE_UNITS = 200 as const;
export const FINAL_REVIEW_MIN_FULL_SOURCE_COPY_CODE_UNITS = 32 as const;

export const FINAL_REVIEW_LIMITS = Object.freeze({
  reasonCodeUnits: FINAL_REVIEW_MAX_REASON_CODE_UNITS,
  inputTextCodeUnits: FINAL_REVIEW_MAX_INPUT_TEXT_CODE_UNITS,
  arrayItems: FINAL_REVIEW_MAX_ARRAY_ITEMS,
  unquotedCopyCodeUnits: FINAL_REVIEW_MAX_UNQUOTED_COPY_CODE_UNITS,
  allowedQuoteCodeUnits: FINAL_REVIEW_MAX_ALLOWED_QUOTE_CODE_UNITS,
  fullSourceCopyMinimumCodeUnits:
    FINAL_REVIEW_MIN_FULL_SOURCE_COPY_CODE_UNITS,
});
