export const FINAL_REVIEW_SCHEMA_VERSION = "0.1.0" as const;

export const CHARLIE_SIGNATURE_REVIEW_INPUT_SCHEMA_VERSION =
  FINAL_REVIEW_SCHEMA_VERSION;
export const CHARLIE_SIGNATURE_REVIEW_CANDIDATE_SCHEMA_VERSION =
  FINAL_REVIEW_SCHEMA_VERSION;
export const CHARLIE_SIGNATURE_REVIEW_RESULT_SCHEMA_VERSION =
  FINAL_REVIEW_SCHEMA_VERSION;
export const CHARLIE_SIGNATURE_REVIEW_ERROR_SCHEMA_VERSION =
  FINAL_REVIEW_SCHEMA_VERSION;

export const MOCK_FINAL_REVIEW_ADAPTER_VERSION = "0.1.0" as const;
